### ISSUE TITLE
🐛[BUG] SyntaxError: Cannot use import statement outside a module, NEXTJS 13

### ISSUE THREAD

**Issue by IcanPressF** [ant-design/pro-components#6525] opened 2023-01-17 20:06 UTC
### 🐛 About Error

Next 13 framework is used, there was an attempt to use pro ant components, unfortunately I get an error, for more details, look at the codesandbox

SyntaxError: Cannot use import statement outside a module
/node_modules/antd/es/skeleton/style/index.js (1)

### 📷 Problem reproduction

https://shortest.link/drl5
Go to /about page 

### 🏞 Desired result

Display components without errors

### 💻 播放代碼

https://shortest.link/drl5
Go to /about page 

### © package.json
```
{
  "private": true,
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@ant-design/icons": "^4.8.0",
    "@ant-design/pro-components": "^2.3.52",
    "@types/qs": "^6.9.7",
    "antd": "^5.0.0",
    "next": "latest",
    "qs": "^6.11.0",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "browser": {
    "fs": false,
    "path": false
  },
  "devDependencies": {
    "@types/node": "18.0.3",
    "@types/react": "18.0.15",
    "@types/react-dom": "18.0.6",
    "typescript": "4.7.4"
  }
}
```

**Comment by UsVfxArtia** [comment] 2023-01-17 20:26
Please help me solve this problem

**Comment by luo3house** [comment] 2023-01-18 13:50
I guess there is an exception during publish, which caused an es import in cjs module. When I rebuild library, it outputs correctly.

**Comment by UnkAtreus** [comment] 2023-01-19 05:48
Issue is still have. Pls help

**Comment by allanlisboa** [comment] 2023-01-19 15:06
I have the same problem

**Comment by UsVfxArtia** [comment] 2023-01-19 15:29
> I guess there is an exception during publish, which caused an es import in cjs module. When I rebuild library, it outputs correctly.
Hello! What do you mean? How to rebuild?

**Comment by UsVfxArtia** [comment] 2023-01-19 15:37
> I guess there is an exception during publish, which caused an es import in cjs module. When I rebuild library, it outputs correctly.

Did u visit /about page? Error occurs there

**Comment by UsVfxArtia** [comment] 2023-01-20 11:35
very sad, seems like it wont be fixed.

**Comment by UnkAtreus** [comment] 2023-01-23 15:03
Yeah it wont be fixed but I installed sub component instead of @ant-design/pro-components

**Comment by Armito** [comment] 2023-02-14 06:36
same problem

**Comment by jkiss** [comment] 2023-02-14 06:36
`SyntaxError: Cannot use import statement outside a module` 心累。。。

**Comment by raptoria** [comment] 2023-02-15 02:26
also having this issue...

**Comment by alexneo2003** [comment] 2023-02-15 12:23
have same issue
my `Content` component contain `PageHeader` component imported from `@ant-design/pro-layout`
after changing root component import to `next/dynamic` issue was gone
 
```diff
- import Content from 'components/pages/Course/Content'
+ import dynamic from 'next/dynamic'
import { useRouter } from 'next/router'

+ const Content = dynamic(async () => await import('components/pages/Course/Content'), {
+  ssr: false,
+ })

function ContentPage() {
  return <Content />
}

export default ContentPage
```

**Comment by piperubio** [comment] 2023-02-18 17:39
From my part, I was able to solve this thanks to the response from @ogienma at #https://github.com/ant-design/pro-components/issues/4852#issuecomment-1364570216 in Next.js v13 with Ant Design v5.

**Comment by chenshuai2144** [comment] 2023-03-06 10:08
> TAutomatically replying with ChatGPT can be attempted, but it cannot be guaranteed to be completely accurate and may not fully address all issues. Please feel free to reply if you have any further questions or concerns.
 > 此回复基于 ChatGPT 自动生成，可以尝试下方案，官方员会在一定时间后继续继续处理。


Great to hear that the issue is resolved for you! Could you please share the solution you used in case others encounter similar issues in the future? Thank you!

**Comment by lyan-ap** [comment] 2023-05-12 08:27
Server Error
SyntaxError: Cannot use import statement outside a module

**Comment by ltienphat1307** [comment] 2023-07-11 02:17
I have the same one

**Comment by Eureka-Sacha** [comment] 2023-07-13 09:05
same to me .

**Comment by chenshuai2144** [comment] 2023-07-15 15:58
The error message "SyntaxError: Cannot use import statement outside a module" typically occurs in a Next.js 13 project when you're trying to use an import statement in a file that is not recognized as a module. In Next.js 13, you need to use the `.js` extension for JavaScript files to be treated as modules.

To resolve this issue, you can try the following steps:

1. Make sure your file has the `.js` extension. For example, if your file is named `example.js`, rename it to `example.js`.

2. Ensure that the file is located in a directory recognized as a module. In Next.js, modules should be placed in the `pages` directory or any subdirectory inside the `pages` directory.

3. If you're trying to import a module from a different file, make sure the imported file also has the `.js` extension and is located in a module recognized directory.

By following these steps, you should be able to resolve the "SyntaxError: Cannot use import statement outside a module" issue in Next.js 13.

**Comment by chenshuai2144** [comment] 2023-07-15 15:59
```
const nextConfig = {
  reactStrictMode: true,
  // es 模块编译
  transpilePackages: ['kitchen-flow-editor', '@ant-design/pro-editor', 'zustand', 'leva'],
```

you can use transpilePackages

**Closed by chenshuai2144** 2023-07-15 15:59 UTC
Labels: AI Reply

**Comment by daoyuly** [comment] 2023-11-21 12:42
When you encounter "SyntaxError: Unexpected token 'export'", "'SyntaxError: Cannot use import statement outside a module'" and other related issues, you need to add the module that exposes the issue to the transpilePackages configuration.

**Comment by pedroSoaresll** [comment] 2023-11-28 20:48
> When you encounter "SyntaxError: Unexpected token 'export'", "'SyntaxError: Cannot use import statement outside a module'" and other related issues, you need to add the module that exposes the issue to the transpilePackages configuration.
> 
> ```
> const nextConfig = {
>   reactStrictMode: true,
>   transpilePackages: [
>     'rc-util',
>     '@ant-design',
>     'kitchen-flow-editor',
>     '@ant-design/pro-editor',
>     'zustand', 'leva', 'antd',
>     'rc-pagination',
>     'rc-picker'
>   ],
> }
> ```

**[solved]**

This helped me to identify and solve a similar problem that was happening to me. Note that the problem is only happening in the Jest environment in my case, in the dev mode and build script it is working correctly without the configuration below:

The weirdest part was that I needed to put the `"@babel/runtime"` into the `transpilePackages` list.

```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  transpilePackages: [
    "antd",
    "rc-util",
    "@babel/runtime",
    "@ant-design/icons",
    "@ant-design/icons-svg",
    "rc-pagination",
    "rc-picker",
    "rc-tree",
    "rc-table",
  ],
};

module.exports = nextConfig;
```

The error that the code above solves is represented by the image below:

<img width="1002" alt="image" src="https://github.com/ant-design/pro-components/assets/11558773/226127e8-c5c7-4cfd-bf78-222f0f96e1bb">

**Comment by JackHammer29** [comment] 2023-12-09 20:22
> > When you encounter "SyntaxError: Unexpected token 'export'", "'SyntaxError: Cannot use import statement outside a module'" and other related issues, you need to add the module that exposes the issue to the transpilePackages configuration.
> > ```
> > const nextConfig = {
> >   reactStrictMode: true,
> >   transpilePackages: [
> >     'rc-util',
> >     '@ant-design',
> >     'kitchen-flow-editor',
> >     '@ant-design/pro-editor',
> >     'zustand', 'leva', 'antd',
> >     'rc-pagination',
> >     'rc-picker'
> >   ],
> > }
> > ```
> 
> **[solved]**
> 
> This helped me to identify and solve a similar problem that was happening to me. Note that the problem is only happening in the Jest environment in my case, in the dev mode and build script it is working correctly without the configuration below:
> 
> The weirdest part was that I needed to put the `"@babel/runtime"` into the `transpilePackages` list.
> 
> ```ts
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   transpilePackages: [
>     "antd",
>     "rc-util",
>     "@babel/runtime",
>     "@ant-design/icons",
>     "@ant-design/icons-svg",
>     "rc-pagination",
>     "rc-picker",
>     "rc-tree",
>     "rc-table",
>   ],
> };
> 
> module.exports = nextConfig;
> ```
> 
> The error that the code above solves is represented by the image below:
> 
> <img alt="image" width="1002" src="https://private-user-images.githubusercontent.com/11558773/286396138-226127e8-c5c7-4cfd-bf78-222f0f96e1bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNTMxOTIsIm5iZiI6MTcwMjE1Mjg5MiwicGF0aCI6Ii8xMTU1ODc3My8yODYzOTYxMzgtMjI2MTI3ZTgtYzVjNy00Y2ZkLWJmNzgtMjIyZjBmOTZlMWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDIwMTQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhY2Q2ZTA2YWI3ODY0Yjk2MWE5YTdiZmNlNmE4ZjJhZmM3MzUwMzhlNjEzYWRjYWIwODVjOTRiYWYwNDUyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k_FSUbBXd3x4NwpSqIACyQ8MMtJmq9pWmH8q_MQBPFs">

For some reason the issue remains for me, babel complaining on build, despite adding it to transpilePackages

**Comment by Haamso** [comment] 2024-02-26 06:53
![Screenshot (253)](https://github.com/ant-design/pro-components/assets/159852062/d67e2c59-d0fb-483a-a1a6-33386bb18f79)

Help me plss !!

**Comment by NullBetaGG** [comment] 2024-02-29 19:59
The same error was happening to me, my import was like this:

`import { Popconfirm } from "antd";`

so I changed it to:

`import { Popconfirm } from "antd/lib";`

and incredibly the webpack error was resolved.

**Comment by colelee** [comment] 2024-03-19 06:09
> The same error was happening to me, my import was like this:
> 
> `import { Popconfirm } from "antd";`
> 
> so I changed it to:
> 
> `import { Popconfirm } from "antd/lib";`
> 
> and incredibly the webpack error was resolved.

why?

**Comment by NullBetaGG** [comment] 2024-03-19 13:03
When you import a module using "antd", webpack looks for the module in the "node_modules" directory and then resolves it based on the main entry point specified in the "package.json" file of the "antd" package. This main entry point could be a JavaScript file or a directory.

In contrast, when you import a module using "antd/lib", webpack directly targets the specific file or directory within the "antd" package without relying on the main entry point specified in "package.json". This can sometimes resolve issues related to how webpack resolves module paths or handles specific files.
