### ISSUE TITLE
@ant-design/pro-utils version 2.16.0 causing node ssr to fail 

### ISSUE THREAD

**Issue by veeramarni** [ant-design/pro-components#8627] opened 2024-08-05 10:21 UTC
提问前先看看：

https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md

### 🔩 所属模块或组件

Nodejs pure esm fails

```
Failed to start server: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/app/node_modules/lodash-es/lodash.js from /home/app/node_modules/@ant-design/pro-utils/lib/transformKeySubmitValue/index.js not supported.
Instead change the require of lodash.js in /home/app/node_modules/@ant-design/pro-utils/lib/transformKeySubmitValue/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/app/node_modules/@ant-design/pro-utils/lib/transformKeySubmitValue/index.js:12:17)
    at Object.<anonymous> (/home/app/node_modules/@ant-design/pro-utils/lib/index.js:480:32)
    at Object.<anonymous> (/home/app/node_modules/@ant-design/pro-layout/lib/components/SiderMenu/BaseMenu.js:17:17)
    at async startServer (file:///home/app/server.js:21:37) {
  code: 'ERR_REQUIRE_ESM'
}
/home/app/node_modules/@ant-design/pro-utils/lib/transformKeySubmitValue/index.js:12
var _lodashEs = require("lodash-es");
                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/app/node_modules/lodash-es/lodash.js from /home/app/node_modules/@ant-design/pro-utils/lib/transformKeySubmitValue/index.js not supported.
Instead change the require of lodash.js in /home/app/node_modules/@ant-design/pro-utils/lib/transformKeySubmitValue/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/app/node_modules/@ant-design/pro-utils/lib/transformKeySubmitValue/index.js:12:17)
    at Object.<anonymous> (/home/app/node_modules/@ant-design/pro-utils/lib/index.js:480:32)
    at Object.<anonymous> (/home/app/node_modules/@ant-design/pro-layout/lib/components/SiderMenu/BaseMenu.js:17:17)
    at async startServer (file:///home/app/server.js:21:37) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.20.4


Could be related to this https://github.com/ant-design/pro-components/commit/9dffa8f7a467475a308bd9c68a6a0632bf300177#diff-c407fc35e4cbdcbe6777dfcb328fdfc7cea2f2e379ff59cfc4270231e6cecfd9R16
```

**Comment by Soumako** [comment] 2024-08-13 02:59
I encounter this problem too. any solutions? nodejs version: 16.17.1

**Comment by navid-kalaei** [comment] 2024-08-13 09:21
The cause of the error is this commit 455b4f1bb1edfd896c04d98c37da6f97fb2428cb. rollback to a version before that which is `7.19.11`

here is the commands:
```sh
yarn remove @ant-design/pro-layout
yarn add  @ant-design/pro-layout@7.19.11
```

## References:
https://github.com/ant-design/pro-components/pull/8606
https://github.com/ant-design/pro-components/commit/455b4f1bb1edfd896c04d98c37da6f97fb2428cb

**Comment by veeramarni** [comment] 2024-09-07 15:56
any update?

**Comment by vojty** [comment] 2024-09-24 07:26
There are actually 2 problems:
1. CJS build uses ESM module `lodash-es` - I believe this should be fixed by replacing `lodash-es` -> `lodash` during the build step
2. ESM build is missing `exports` definition in `package.json`, which causes problems when using for example `vitest` (`vitest` uses nodejs resolver that detects ESM by `exports` attribute, not `module`). The packages are recognized as CJS which causes 1. again

I have prepared a fix for 2. here https://github.com/ant-design/pro-components/pull/8738 @chenshuai2144 Could you please take a look?

**Comment by chenshuai2144** [comment] 2024-09-26 17:07
我将会处理发布新的版本

**Closed** 2024-09-29 02:16 UTC
